import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const SYSTEM_CATEGORIES = [
  { name: 'Food & Dining',        color: '#f97316', icon: 'UtensilsCrossed', isIncome: false, sortOrder: 1,  masterKey: 'FOOD'         },
  { name: 'Groceries',            color: '#fb923c', icon: 'ShoppingCart',    isIncome: false, sortOrder: 2,  masterKey: 'GROCERY'      },
  { name: 'Housing',              color: '#6366f1', icon: 'Home',            isIncome: false, sortOrder: 3,  masterKey: 'HOME'         },
  { name: 'Transport',            color: '#3b82f6', icon: 'Car',             isIncome: false, sortOrder: 4,  masterKey: 'TRANSPORT'    },
  { name: 'Entertainment',        color: '#ec4899', icon: 'Film',            isIncome: false, sortOrder: 5,  masterKey: 'ENTERTAINMENT'},
  { name: 'Shopping',             color: '#a855f7', icon: 'ShoppingBag',     isIncome: false, sortOrder: 6,  masterKey: 'SHOPPING'     },
  { name: 'Health',               color: '#10b981', icon: 'HeartPulse',      isIncome: false, sortOrder: 7,  masterKey: 'HEALTH'       },
  { name: 'Utilities',            color: '#14b8a6', icon: 'Zap',             isIncome: false, sortOrder: 8,  masterKey: 'HOME'         },
  { name: 'Subscriptions',        color: '#f43f5e', icon: 'CreditCard',      isIncome: false, sortOrder: 9,  masterKey: 'DIGITAL'      },
  { name: 'Personal Care',        color: '#8b5cf6', icon: 'Scissors',        isIncome: false, sortOrder: 10, masterKey: 'PERSONAL_CARE'},
  { name: 'Education',            color: '#0ea5e9', icon: 'BookOpen',        isIncome: false, sortOrder: 11, masterKey: 'EDUCATION'    },
  { name: 'Travel',               color: '#f59e0b', icon: 'Plane',           isIncome: false, sortOrder: 12, masterKey: 'TRAVEL'       },
  { name: 'Insurance',            color: '#64748b', icon: 'Shield',          isIncome: false, sortOrder: 13, masterKey: 'FINANCIAL'    },
  { name: 'Pets',                 color: '#84cc16', icon: 'PawPrint',        isIncome: false, sortOrder: 14, masterKey: 'PETS'         },
  { name: 'Gifts & Charity',      color: '#ef4444', icon: 'Gift',            isIncome: false, sortOrder: 15, masterKey: 'SOCIAL'       },
  { name: 'Fees & Charges',       color: '#94a3b8', icon: 'DollarSign',      isIncome: false, sortOrder: 16, masterKey: 'FINANCIAL'    },
  { name: 'Income',               color: '#22c55e', icon: 'TrendingUp',      isIncome: true,  sortOrder: 17, masterKey: null           },
  { name: 'Fast Food',            color: '#ef4444', icon: 'Utensils',        isIncome: false, sortOrder: 2,  masterKey: 'FAST_FOOD'    },
  { name: 'Alcohol',              color: '#8b5cf6', icon: 'Wine',            isIncome: false, sortOrder: 20, masterKey: 'ALCOHOL'      },
  { name: 'Cigarettes & Tobacco', color: '#78716c', icon: 'Ban',             isIncome: false, sortOrder: 21, masterKey: 'TOBACCO'      },
  { name: 'Transfer',             color: '#78716c', icon: 'ArrowLeftRight',  isIncome: false, isTransfer: true, sortOrder: 22, masterKey: null },
  { name: 'Other',                color: '#94a3b8', icon: 'Package',         isIncome: false, sortOrder: 23, masterKey: null           },
  { name: 'Coffee',               color: '#d97706', icon: 'Coffee',          isIncome: false, sortOrder: 24, masterKey: 'COFFEE'       },
  { name: 'Credit Card Payment',  color: '#6366f1', icon: 'CreditCard',      isIncome: false, isTransfer: true, sortOrder: 25, masterKey: 'FINANCIAL' },
]

type CategoryRuleInput = {
  matchType: 'exact' | 'contains' | 'regex'
  matchValue: string
  priority: number
}

const RULES_BY_CATEGORY: Record<string, CategoryRuleInput[]> = {
  'Food & Dining': [
    { matchType: 'contains', matchValue: 'mcdonald', priority: 10 },
    { matchType: 'contains', matchValue: 'mcdonalds', priority: 10 },
    { matchType: 'contains', matchValue: 'burger king', priority: 10 },
    { matchType: 'contains', matchValue: 'wendy', priority: 10 },
    { matchType: 'contains', matchValue: 'taco bell', priority: 10 },
    { matchType: 'contains', matchValue: 'domino', priority: 10 },
    { matchType: 'contains', matchValue: 'pizza hut', priority: 10 },
    { matchType: 'contains', matchValue: 'subway', priority: 10 },
    { matchType: 'contains', matchValue: 'chipotle', priority: 10 },
    { matchType: 'contains', matchValue: 'starbucks', priority: 10 },
    { matchType: 'contains', matchValue: 'dunkin', priority: 10 },
    { matchType: 'contains', matchValue: 'doordash', priority: 10 },
    { matchType: 'contains', matchValue: 'uber eats', priority: 10 },
    { matchType: 'contains', matchValue: 'ubereats', priority: 10 },
    { matchType: 'contains', matchValue: 'grubhub', priority: 10 },
    { matchType: 'contains', matchValue: 'postmates', priority: 10 },
    { matchType: 'contains', matchValue: 'instacart restaurant', priority: 10 },
    { matchType: 'contains', matchValue: 'panera', priority: 10 },
    { matchType: 'contains', matchValue: 'chick-fil-a', priority: 10 },
    { matchType: 'contains', matchValue: 'chickfila', priority: 10 },
    { matchType: 'contains', matchValue: 'kfc', priority: 10 },
    { matchType: 'contains', matchValue: 'popeyes', priority: 10 },
    { matchType: 'contains', matchValue: 'applebee', priority: 10 },
    { matchType: 'contains', matchValue: 'olive garden', priority: 10 },
    { matchType: 'contains', matchValue: 'chili', priority: 10 },
    { matchType: 'contains', matchValue: 'denny', priority: 10 },
    { matchType: 'contains', matchValue: 'ihop', priority: 10 },
    { matchType: 'contains', matchValue: 'waffle house', priority: 10 },
    { matchType: 'contains', matchValue: 'red lobster', priority: 10 },
    { matchType: 'contains', matchValue: 'restaurant', priority: 8 },
    { matchType: 'contains', matchValue: 'sushi', priority: 8 },
    { matchType: 'contains', matchValue: 'bistro', priority: 8 },
    { matchType: 'contains', matchValue: 'diner', priority: 8 },
    { matchType: 'contains', matchValue: 'grill', priority: 7 },
    { matchType: 'contains', matchValue: 'eatery', priority: 7 },
    { matchType: 'contains', matchValue: 'cafe', priority: 7 },
    { matchType: 'contains', matchValue: 'bakery', priority: 7 },
    { matchType: 'contains', matchValue: 'coffee', priority: 7 },
    { matchType: 'contains', matchValue: 'smoothie', priority: 7 },
    { matchType: 'contains', matchValue: 'juice bar', priority: 7 },
    { matchType: 'contains', matchValue: 'boba', priority: 7 },
    { matchType: 'contains', matchValue: 'bbq', priority: 7 },
  ],
  'Groceries': [
    { matchType: 'contains', matchValue: 'whole foods', priority: 10 },
    { matchType: 'contains', matchValue: 'wholefoods', priority: 10 },
    { matchType: 'contains', matchValue: 'wholefds', priority: 10 },
    { matchType: 'contains', matchValue: 'trader joe', priority: 10 },
    { matchType: 'contains', matchValue: 'kroger', priority: 10 },
    { matchType: 'contains', matchValue: 'safeway', priority: 10 },
    { matchType: 'contains', matchValue: 'publix', priority: 10 },
    { matchType: 'contains', matchValue: 'aldi', priority: 10 },
    { matchType: 'contains', matchValue: 'costco', priority: 10 },
    { matchType: 'contains', matchValue: 'sam\'s club', priority: 10 },
    { matchType: 'contains', matchValue: 'sams club', priority: 10 },
    { matchType: 'contains', matchValue: 'h-e-b', priority: 10 },
    { matchType: 'contains', matchValue: 'heb', priority: 10 },
    { matchType: 'contains', matchValue: 'wegmans', priority: 10 },
    { matchType: 'contains', matchValue: 'sprouts', priority: 10 },
    { matchType: 'contains', matchValue: 'meijer', priority: 10 },
    { matchType: 'contains', matchValue: 'food lion', priority: 10 },
    { matchType: 'contains', matchValue: 'instacart', priority: 9 },
    { matchType: 'contains', matchValue: 'grocery', priority: 8 },
    { matchType: 'contains', matchValue: 'supermarket', priority: 8 },
    { matchType: 'contains', matchValue: 'market', priority: 6 },
  ],
  'Housing': [
    { matchType: 'contains', matchValue: 'rent', priority: 10 },
    { matchType: 'contains', matchValue: 'mortgage', priority: 10 },
    { matchType: 'contains', matchValue: 'hoa', priority: 9 },
    { matchType: 'contains', matchValue: 'home depot', priority: 9 },
    { matchType: 'contains', matchValue: 'homedepot', priority: 9 },
    { matchType: 'contains', matchValue: 'lowe\'s', priority: 9 },
    { matchType: 'contains', matchValue: 'lowes', priority: 9 },
    { matchType: 'contains', matchValue: 'ace hardware', priority: 8 },
    { matchType: 'contains', matchValue: 'hardware', priority: 7 },
    { matchType: 'contains', matchValue: 'property', priority: 7 },
    { matchType: 'contains', matchValue: 'apartment', priority: 7 },
  ],
  'Transport': [
    { matchType: 'contains', matchValue: 'uber', priority: 10 },
    { matchType: 'contains', matchValue: 'lyft', priority: 10 },
    { matchType: 'contains', matchValue: 'gas station', priority: 10 },
    { matchType: 'contains', matchValue: 'shell', priority: 9 },
    { matchType: 'contains', matchValue: 'chevron', priority: 9 },
    { matchType: 'contains', matchValue: 'bp gas', priority: 9 },
    { matchType: 'contains', matchValue: 'exxon', priority: 9 },
    { matchType: 'contains', matchValue: 'mobil', priority: 9 },
    { matchType: 'contains', matchValue: 'speedway', priority: 9 },
    { matchType: 'contains', matchValue: 'marathon gas', priority: 9 },
    { matchType: 'contains', matchValue: 'mta', priority: 9 },
    { matchType: 'contains', matchValue: 'metro', priority: 8 },
    { matchType: 'contains', matchValue: 'transit', priority: 8 },
    { matchType: 'contains', matchValue: 'parking', priority: 8 },
    { matchType: 'contains', matchValue: 'auto', priority: 7 },
    { matchType: 'contains', matchValue: 'ezpass', priority: 9 },
    { matchType: 'contains', matchValue: 'ez pass', priority: 9 },
    { matchType: 'contains', matchValue: 'toll', priority: 8 },
    { matchType: 'contains', matchValue: 'car wash', priority: 8 },
    { matchType: 'contains', matchValue: 'jiffy lube', priority: 9 },
    { matchType: 'contains', matchValue: 'valvoline', priority: 9 },
    { matchType: 'contains', matchValue: 'amtrak', priority: 9 },
    { matchType: 'contains', matchValue: 'airline', priority: 8 },
    { matchType: 'contains', matchValue: 'delta air', priority: 9 },
    { matchType: 'contains', matchValue: 'united air', priority: 9 },
    { matchType: 'contains', matchValue: 'southwest air', priority: 9 },
    { matchType: 'contains', matchValue: 'american air', priority: 9 },
  ],
  'Entertainment': [
    { matchType: 'contains', matchValue: 'netflix', priority: 10 },
    { matchType: 'contains', matchValue: 'hulu', priority: 10 },
    { matchType: 'contains', matchValue: 'disney+', priority: 10 },
    { matchType: 'contains', matchValue: 'disneyplus', priority: 10 },
    { matchType: 'contains', matchValue: 'hbo', priority: 10 },
    { matchType: 'contains', matchValue: 'max streaming', priority: 10 },
    { matchType: 'contains', matchValue: 'paramount', priority: 10 },
    { matchType: 'contains', matchValue: 'peacock', priority: 10 },
    { matchType: 'contains', matchValue: 'cinema', priority: 9 },
    { matchType: 'contains', matchValue: 'movie theater', priority: 9 },
    { matchType: 'contains', matchValue: 'amc theater', priority: 9 },
    { matchType: 'contains', matchValue: 'regal cinema', priority: 9 },
    { matchType: 'contains', matchValue: 'ticketmaster', priority: 9 },
    { matchType: 'contains', matchValue: 'stubhub', priority: 9 },
    { matchType: 'contains', matchValue: 'concert', priority: 8 },
    { matchType: 'contains', matchValue: 'eventbrite', priority: 8 },
    { matchType: 'contains', matchValue: 'steam', priority: 8 },
    { matchType: 'contains', matchValue: 'playstation', priority: 8 },
    { matchType: 'contains', matchValue: 'xbox', priority: 8 },
    { matchType: 'contains', matchValue: 'nintendo', priority: 8 },
    { matchType: 'contains', matchValue: 'apple itunes', priority: 9 },
    { matchType: 'contains', matchValue: 'google play', priority: 9 },
    { matchType: 'contains', matchValue: 'spotify', priority: 10 },
    { matchType: 'contains', matchValue: 'apple music', priority: 10 },
    { matchType: 'contains', matchValue: 'bowling', priority: 8 },
    { matchType: 'contains', matchValue: 'escape room', priority: 8 },
    { matchType: 'contains', matchValue: 'dave & buster', priority: 9 },
    { matchType: 'contains', matchValue: 'bar ', priority: 7 },
  ],
  'Shopping': [
    { matchType: 'contains', matchValue: 'amazon', priority: 10 },
    { matchType: 'contains', matchValue: 'amzn', priority: 10 },
    { matchType: 'contains', matchValue: 'walmart', priority: 9 },
    { matchType: 'contains', matchValue: 'target', priority: 9 },
    { matchType: 'contains', matchValue: 'best buy', priority: 9 },
    { matchType: 'contains', matchValue: 'bestbuy', priority: 9 },
    { matchType: 'contains', matchValue: 'apple store', priority: 9 },
    { matchType: 'contains', matchValue: 'apple.com', priority: 9 },
    { matchType: 'contains', matchValue: 'ebay', priority: 9 },
    { matchType: 'contains', matchValue: 'etsy', priority: 9 },
    { matchType: 'contains', matchValue: 'wayfair', priority: 9 },
    { matchType: 'contains', matchValue: 'ikea', priority: 9 },
    { matchType: 'contains', matchValue: 'h&m', priority: 9 },
    { matchType: 'contains', matchValue: 'zara', priority: 9 },
    { matchType: 'contains', matchValue: 'gap', priority: 8 },
    { matchType: 'contains', matchValue: 'old navy', priority: 9 },
    { matchType: 'contains', matchValue: 'banana republic', priority: 9 },
    { matchType: 'contains', matchValue: 'nordstrom', priority: 9 },
    { matchType: 'contains', matchValue: 'macy', priority: 9 },
    { matchType: 'contains', matchValue: 'tj maxx', priority: 9 },
    { matchType: 'contains', matchValue: 'tjmaxx', priority: 9 },
    { matchType: 'contains', matchValue: 'marshalls', priority: 9 },
    { matchType: 'contains', matchValue: 'ross store', priority: 9 },
    { matchType: 'contains', matchValue: 'dollar tree', priority: 8 },
    { matchType: 'contains', matchValue: 'dollar general', priority: 8 },
    { matchType: 'contains', matchValue: 'five below', priority: 8 },
    { matchType: 'contains', matchValue: 'shopify', priority: 7 },
    { matchType: 'contains', matchValue: 'paypal', priority: 6 },
  ],
  'Health': [
    { matchType: 'contains', matchValue: 'cvs', priority: 10 },
    { matchType: 'contains', matchValue: 'walgreens', priority: 10 },
    { matchType: 'contains', matchValue: 'rite aid', priority: 10 },
    { matchType: 'contains', matchValue: 'pharmacy', priority: 10 },
    { matchType: 'contains', matchValue: 'medical', priority: 9 },
    { matchType: 'contains', matchValue: 'hospital', priority: 9 },
    { matchType: 'contains', matchValue: 'clinic', priority: 9 },
    { matchType: 'contains', matchValue: 'doctor', priority: 9 },
    { matchType: 'contains', matchValue: 'dental', priority: 9 },
    { matchType: 'contains', matchValue: 'dentist', priority: 9 },
    { matchType: 'contains', matchValue: 'vision', priority: 8 },
    { matchType: 'contains', matchValue: 'optometrist', priority: 9 },
    { matchType: 'contains', matchValue: 'urgent care', priority: 9 },
    { matchType: 'contains', matchValue: 'lab corp', priority: 9 },
    { matchType: 'contains', matchValue: 'quest diagnostics', priority: 9 },
    { matchType: 'contains', matchValue: 'gym', priority: 8 },
    { matchType: 'contains', matchValue: 'planet fitness', priority: 9 },
    { matchType: 'contains', matchValue: 'anytime fitness', priority: 9 },
    { matchType: 'contains', matchValue: 'crunch fitness', priority: 9 },
    { matchType: 'contains', matchValue: 'yoga', priority: 8 },
    { matchType: 'contains', matchValue: 'vitamins', priority: 8 },
    { matchType: 'contains', matchValue: 'prescription', priority: 9 },
    { matchType: 'contains', matchValue: 'rx', priority: 7 },
  ],
  'Utilities': [
    { matchType: 'contains', matchValue: 'electric', priority: 10 },
    { matchType: 'contains', matchValue: 'gas bill', priority: 10 },
    { matchType: 'contains', matchValue: 'water bill', priority: 10 },
    { matchType: 'contains', matchValue: 'utility', priority: 10 },
    { matchType: 'contains', matchValue: 'internet', priority: 9 },
    { matchType: 'contains', matchValue: 'comcast', priority: 9 },
    { matchType: 'contains', matchValue: 'xfinity', priority: 9 },
    { matchType: 'contains', matchValue: 'spectrum', priority: 9 },
    { matchType: 'contains', matchValue: 'at&t', priority: 9 },
    { matchType: 'contains', matchValue: 'verizon', priority: 9 },
    { matchType: 'contains', matchValue: 't-mobile', priority: 9 },
    { matchType: 'contains', matchValue: 'tmobile', priority: 9 },
    { matchType: 'contains', matchValue: 'sprint', priority: 9 },
    { matchType: 'contains', matchValue: 'phone bill', priority: 9 },
    { matchType: 'contains', matchValue: 'cable', priority: 8 },
    { matchType: 'contains', matchValue: 'directv', priority: 9 },
    { matchType: 'contains', matchValue: 'dish network', priority: 9 },
    { matchType: 'contains', matchValue: 'pge', priority: 8 },
    { matchType: 'contains', matchValue: 'con edison', priority: 9 },
    { matchType: 'contains', matchValue: 'comed', priority: 9 },
  ],
  'Subscriptions': [
    { matchType: 'contains', matchValue: 'adobe', priority: 10 },
    { matchType: 'contains', matchValue: 'microsoft 365', priority: 10 },
    { matchType: 'contains', matchValue: 'microsoft office', priority: 10 },
    { matchType: 'contains', matchValue: 'dropbox', priority: 10 },
    { matchType: 'contains', matchValue: 'icloud', priority: 10 },
    { matchType: 'contains', matchValue: 'google one', priority: 10 },
    { matchType: 'contains', matchValue: 'amazon prime', priority: 10 },
    { matchType: 'contains', matchValue: 'amazon.com prime', priority: 10 },
    { matchType: 'contains', matchValue: 'linkedin premium', priority: 10 },
    { matchType: 'contains', matchValue: 'audible', priority: 10 },
    { matchType: 'contains', matchValue: 'kindle', priority: 9 },
    { matchType: 'contains', matchValue: 'nytimes', priority: 9 },
    { matchType: 'contains', matchValue: 'new york times', priority: 9 },
    { matchType: 'contains', matchValue: 'wsj', priority: 9 },
    { matchType: 'contains', matchValue: 'wall street journal', priority: 9 },
    { matchType: 'contains', matchValue: 'subscription', priority: 7 },
    { matchType: 'contains', matchValue: 'monthly plan', priority: 7 },
  ],
  'Personal Care': [
    { matchType: 'contains', matchValue: 'salon', priority: 9 },
    { matchType: 'contains', matchValue: 'hair cut', priority: 9 },
    { matchType: 'contains', matchValue: 'haircut', priority: 9 },
    { matchType: 'contains', matchValue: 'barbershop', priority: 9 },
    { matchType: 'contains', matchValue: 'nail salon', priority: 9 },
    { matchType: 'contains', matchValue: 'spa', priority: 8 },
    { matchType: 'contains', matchValue: 'massage', priority: 8 },
    { matchType: 'contains', matchValue: 'ulta', priority: 9 },
    { matchType: 'contains', matchValue: 'sephora', priority: 9 },
  ],
  'Education': [
    { matchType: 'contains', matchValue: 'tuition', priority: 10 },
    { matchType: 'contains', matchValue: 'university', priority: 9 },
    { matchType: 'contains', matchValue: 'college', priority: 9 },
    { matchType: 'contains', matchValue: 'student loan', priority: 10 },
    { matchType: 'contains', matchValue: 'udemy', priority: 9 },
    { matchType: 'contains', matchValue: 'coursera', priority: 9 },
    { matchType: 'contains', matchValue: 'skillshare', priority: 9 },
    { matchType: 'contains', matchValue: 'duolingo', priority: 9 },
    { matchType: 'contains', matchValue: 'chegg', priority: 9 },
    { matchType: 'contains', matchValue: 'textbook', priority: 8 },
    { matchType: 'contains', matchValue: 'school', priority: 7 },
    { matchType: 'contains', matchValue: 'learning', priority: 6 },
  ],
  'Travel': [
    { matchType: 'contains', matchValue: 'hotel', priority: 10 },
    { matchType: 'contains', matchValue: 'airbnb', priority: 10 },
    { matchType: 'contains', matchValue: 'vrbo', priority: 10 },
    { matchType: 'contains', matchValue: 'marriott', priority: 9 },
    { matchType: 'contains', matchValue: 'hilton', priority: 9 },
    { matchType: 'contains', matchValue: 'hyatt', priority: 9 },
    { matchType: 'contains', matchValue: 'expedia', priority: 9 },
    { matchType: 'contains', matchValue: 'booking.com', priority: 9 },
    { matchType: 'contains', matchValue: 'priceline', priority: 9 },
    { matchType: 'contains', matchValue: 'kayak', priority: 8 },
  ],
  'Insurance': [
    { matchType: 'contains', matchValue: 'insurance', priority: 10 },
    { matchType: 'contains', matchValue: 'geico', priority: 10 },
    { matchType: 'contains', matchValue: 'progressive', priority: 9 },
    { matchType: 'contains', matchValue: 'allstate', priority: 9 },
    { matchType: 'contains', matchValue: 'state farm', priority: 9 },
    { matchType: 'contains', matchValue: 'farmers ins', priority: 9 },
    { matchType: 'contains', matchValue: 'liberty mutual', priority: 9 },
    { matchType: 'contains', matchValue: 'health insurance', priority: 10 },
    { matchType: 'contains', matchValue: 'premium', priority: 6 },
  ],
  'Pets': [
    { matchType: 'contains', matchValue: 'petco', priority: 10 },
    { matchType: 'contains', matchValue: 'petsmart', priority: 10 },
    { matchType: 'contains', matchValue: 'chewy', priority: 10 },
    { matchType: 'contains', matchValue: 'veterinary', priority: 10 },
    { matchType: 'contains', matchValue: 'vet clinic', priority: 10 },
    { matchType: 'contains', matchValue: 'animal hospital', priority: 9 },
    { matchType: 'contains', matchValue: 'pet store', priority: 9 },
    { matchType: 'contains', matchValue: 'petmd', priority: 9 },
  ],
  'Gifts & Charity': [
    { matchType: 'contains', matchValue: 'donation', priority: 10 },
    { matchType: 'contains', matchValue: 'charity', priority: 10 },
    { matchType: 'contains', matchValue: 'gofundme', priority: 10 },
    { matchType: 'contains', matchValue: 'venmo', priority: 7 },
    { matchType: 'contains', matchValue: 'zelle', priority: 7 },
    { matchType: 'contains', matchValue: 'cashapp', priority: 7 },
    { matchType: 'contains', matchValue: 'cash app', priority: 7 },
  ],
  'Fees & Charges': [
    { matchType: 'contains', matchValue: 'service fee', priority: 10 },
    { matchType: 'contains', matchValue: 'late fee', priority: 10 },
    { matchType: 'contains', matchValue: 'overdraft', priority: 10 },
    { matchType: 'contains', matchValue: 'bank fee', priority: 10 },
    { matchType: 'contains', matchValue: 'atm fee', priority: 10 },
    { matchType: 'contains', matchValue: 'wire fee', priority: 9 },
    { matchType: 'contains', matchValue: 'foreign transaction', priority: 9 },
    { matchType: 'contains', matchValue: 'interest charge', priority: 9 },
    { matchType: 'contains', matchValue: 'annual fee', priority: 9 },
    { matchType: 'contains', matchValue: 'maintenance fee', priority: 9 },
  ],
  'Income': [
    { matchType: 'contains', matchValue: 'direct deposit', priority: 10 },
    { matchType: 'contains', matchValue: 'payroll', priority: 10 },
    { matchType: 'contains', matchValue: 'salary', priority: 10 },
    { matchType: 'contains', matchValue: 'employer', priority: 9 },
    { matchType: 'contains', matchValue: 'irs', priority: 9 },
    { matchType: 'contains', matchValue: 'tax refund', priority: 10 },
    { matchType: 'contains', matchValue: 'refund', priority: 8 },
    { matchType: 'contains', matchValue: 'reimbursement', priority: 9 },
    { matchType: 'contains', matchValue: 'interest earned', priority: 9 },
    { matchType: 'contains', matchValue: 'dividend', priority: 9 },
    { matchType: 'contains', matchValue: 'social security', priority: 9 },
    { matchType: 'contains', matchValue: 'unemployment', priority: 9 },
  ],
  'Fast Food': [
    { matchType: 'contains', matchValue: 'mcdonald',       priority: 12 },
    { matchType: 'contains', matchValue: 'mcdonalds',      priority: 12 },
    { matchType: 'contains', matchValue: 'burger king',    priority: 12 },
    { matchType: 'contains', matchValue: 'wendys',         priority: 12 },
    { matchType: 'contains', matchValue: "wendy's",        priority: 12 },
    { matchType: 'contains', matchValue: 'taco bell',      priority: 12 },
    { matchType: 'contains', matchValue: 'kfc',            priority: 12 },
    { matchType: 'contains', matchValue: 'popeyes',        priority: 12 },
    { matchType: 'contains', matchValue: 'chick-fil-a',    priority: 12 },
    { matchType: 'contains', matchValue: 'chickfila',      priority: 12 },
    { matchType: 'contains', matchValue: 'five guys',      priority: 12 },
    { matchType: 'contains', matchValue: 'shake shack',    priority: 12 },
    { matchType: 'contains', matchValue: 'in-n-out',       priority: 12 },
    { matchType: 'contains', matchValue: 'jack in the box',priority: 12 },
    { matchType: 'contains', matchValue: 'hardees',        priority: 12 },
    { matchType: 'contains', matchValue: 'carls jr',       priority: 12 },
    { matchType: 'contains', matchValue: 'del taco',       priority: 12 },
    { matchType: 'contains', matchValue: 'whataburger',    priority: 12 },
    { matchType: 'contains', matchValue: 'dairy queen',    priority: 12 },
    { matchType: 'contains', matchValue: 'papa john',      priority: 12 },
    { matchType: 'contains', matchValue: 'little caesar',  priority: 12 },
    { matchType: 'contains', matchValue: 'jimmy john',     priority: 12 },
    { matchType: 'contains', matchValue: 'jersey mike',    priority: 12 },
    { matchType: 'contains', matchValue: 'arbys',          priority: 12 },
    { matchType: 'contains', matchValue: 'wingstop',       priority: 12 },
    { matchType: 'contains', matchValue: 'bojangles',      priority: 12 },
    { matchType: 'contains', matchValue: 'raising cane',   priority: 12 },
    { matchType: 'contains', matchValue: 'sonic drive',    priority: 12 },
    { matchType: 'contains', matchValue: 'dominos',        priority: 12 },
    { matchType: 'contains', matchValue: 'pizza hut',      priority: 12 },
    { matchType: 'contains', matchValue: 'subway',         priority: 12 },
    { matchType: 'contains', matchValue: 'panda express',  priority: 12 },
    { matchType: 'contains', matchValue: 'panera',         priority: 12 },
    { matchType: 'contains', matchValue: 'qdoba',          priority: 12 },
  ],
  'Alcohol': [
    { matchType: 'contains', matchValue: 'total wine',        priority: 12 },
    { matchType: 'contains', matchValue: 'totalwine',         priority: 12 },
    { matchType: 'contains', matchValue: 'bevmo',             priority: 12 },
    { matchType: 'contains', matchValue: 'binny',             priority: 12 },
    { matchType: 'contains', matchValue: 'liquor store',      priority: 12 },
    { matchType: 'contains', matchValue: 'wine & spirits',    priority: 12 },
    { matchType: 'contains', matchValue: 'wine and spirits',  priority: 12 },
    { matchType: 'contains', matchValue: 'abc fine wine',     priority: 12 },
    { matchType: 'contains', matchValue: 'abc liquor',        priority: 12 },
    { matchType: 'contains', matchValue: 'package store',     priority: 12 },
    { matchType: 'contains', matchValue: 'state store',       priority: 12 },
    { matchType: 'contains', matchValue: "spec's",            priority: 12 },
    { matchType: 'contains', matchValue: 'total beverage',    priority: 12 },
    { matchType: 'contains', matchValue: 'brewery',           priority: 11 },
    { matchType: 'contains', matchValue: 'winery',            priority: 11 },
    { matchType: 'contains', matchValue: 'distillery',        priority: 11 },
    { matchType: 'contains', matchValue: 'wine bar',          priority: 11 },
    { matchType: 'contains', matchValue: 'drizly',            priority: 12 },
  ],
  'Cigarettes & Tobacco': [
    { matchType: 'contains', matchValue: 'tobacco',        priority: 12 },
    { matchType: 'contains', matchValue: 'cigarette',      priority: 12 },
    { matchType: 'contains', matchValue: 'cigar',          priority: 12 },
    { matchType: 'contains', matchValue: 'smoke shop',     priority: 12 },
    { matchType: 'contains', matchValue: 'smokeshop',      priority: 12 },
    { matchType: 'contains', matchValue: 'vape shop',      priority: 12 },
    { matchType: 'contains', matchValue: 'vapeshop',       priority: 12 },
    { matchType: 'contains', matchValue: 'vape store',     priority: 12 },
    { matchType: 'contains', matchValue: 'juul',           priority: 12 },
    { matchType: 'contains', matchValue: 'e-cigarette',    priority: 12 },
    { matchType: 'contains', matchValue: 'nicotine',       priority: 12 },
    { matchType: 'contains', matchValue: 'marlboro',       priority: 12 },
  ],
  'Transfer': [
    { matchType: 'contains', matchValue: 'transfer', priority: 10 },
    { matchType: 'contains', matchValue: 'payment thank you', priority: 10 },
    { matchType: 'contains', matchValue: 'autopay', priority: 10 },
    { matchType: 'contains', matchValue: 'auto pay', priority: 10 },
    { matchType: 'contains', matchValue: 'online payment', priority: 8 },
    { matchType: 'contains', matchValue: 'bill payment', priority: 8 },
    { matchType: 'regex', matchValue: '^(deposit|withdrawal)\\s+from', priority: 9 },
  ],
  'Coffee': [
    { matchType: 'contains', matchValue: 'starbucks',         priority: 12 },
    { matchType: 'contains', matchValue: 'dunkin',            priority: 12 },
    { matchType: 'contains', matchValue: 'dutch bros',        priority: 12 },
    { matchType: 'contains', matchValue: "peet's coffee",     priority: 12 },
    { matchType: 'contains', matchValue: 'peets coffee',      priority: 12 },
    { matchType: 'contains', matchValue: 'caribou coffee',    priority: 12 },
    { matchType: 'contains', matchValue: 'coffee bean',       priority: 12 },
    { matchType: 'contains', matchValue: 'tim hortons',       priority: 12 },
    { matchType: 'contains', matchValue: 'blue bottle',       priority: 12 },
    { matchType: 'contains', matchValue: 'intelligentsia',    priority: 12 },
    { matchType: 'contains', matchValue: 'verve coffee',      priority: 12 },
    { matchType: 'contains', matchValue: 'philz coffee',      priority: 12 },
    { matchType: 'contains', matchValue: 'la madeleine',      priority: 11 },
    { matchType: 'contains', matchValue: 'coffee shop',       priority: 10 },
    { matchType: 'contains', matchValue: 'espresso',          priority: 10 },
    { matchType: 'contains', matchValue: 'coffee',            priority: 9  },
    { matchType: 'contains', matchValue: 'café',              priority: 9  },
    { matchType: 'contains', matchValue: 'cafe',              priority: 8  },
    { matchType: 'contains', matchValue: 'boba',              priority: 8  },
    { matchType: 'contains', matchValue: 'bubble tea',        priority: 8  },
    { matchType: 'contains', matchValue: 'tea house',         priority: 8  },
  ],
  'Credit Card Payment': [
    { matchType: 'contains', matchValue: 'credit card payment', priority: 12 },
    { matchType: 'contains', matchValue: 'card payment',        priority: 12 },
    { matchType: 'contains', matchValue: 'payment thank you',   priority: 12 },
    { matchType: 'contains', matchValue: 'autopay',             priority: 12 },
    { matchType: 'contains', matchValue: 'auto pay',            priority: 12 },
    { matchType: 'contains', matchValue: 'visa payment',        priority: 12 },
    { matchType: 'contains', matchValue: 'mastercard payment',  priority: 12 },
    { matchType: 'contains', matchValue: 'amex payment',        priority: 12 },
    { matchType: 'contains', matchValue: 'american express payment', priority: 12 },
    { matchType: 'contains', matchValue: 'discover payment',    priority: 12 },
    { matchType: 'contains', matchValue: 'chase payment',       priority: 12 },
    { matchType: 'contains', matchValue: 'citi payment',        priority: 12 },
    { matchType: 'contains', matchValue: 'capital one payment', priority: 12 },
  ],
}

async function main() {
  console.log('Seeding database...')

  // Update existing system categories to use Lucide icon names
  for (const cat of SYSTEM_CATEGORIES) {
    await prisma.category.updateMany({
      where: { name: cat.name, isSystem: true, userId: null },
      data: { icon: cat.icon, color: cat.color, masterKey: cat.masterKey ?? null },
    })
  }
  console.log('  Updated existing system category icons to Lucide names')

  // Insert system categories
  const categoryMap: Record<string, string> = {}

  for (const cat of SYSTEM_CATEGORIES) {
    const existing = await prisma.category.findFirst({
      where: { name: cat.name, isSystem: true, userId: null }
    })
    if (existing) {
      categoryMap[cat.name] = existing.id
      continue
    }
    const created = await prisma.category.create({
      data: {
        name: cat.name,
        color: cat.color,
        icon: cat.icon,
        isIncome: cat.isIncome ?? false,
        isTransfer: (cat as any).isTransfer ?? false,
        isSystem: true,
        sortOrder: cat.sortOrder,
        masterKey: cat.masterKey ?? null,
        userId: null,
      }
    })
    categoryMap[cat.name] = created.id
    console.log(`  Created category: ${cat.name}`)
  }

  // Insert category rules
  let ruleCount = 0
  for (const [catName, rules] of Object.entries(RULES_BY_CATEGORY)) {
    const catId = categoryMap[catName]
    if (!catId) continue

    for (const rule of rules) {
      const existing = await prisma.categoryRule.findFirst({
        where: { categoryId: catId, matchValue: rule.matchValue, isSystem: true }
      })
      if (existing) continue

      await prisma.categoryRule.create({
        data: {
          categoryId: catId,
          matchType: rule.matchType,
          matchValue: rule.matchValue,
          priority: rule.priority,
          isSystem: true,
          userId: null,
        }
      })
      ruleCount++
    }
  }

  console.log(`  Created ${ruleCount} categorization rules`)
  console.log('Seeding complete!')
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
