import type { CorePersonalityId, PremiumPersonalityId, TraitId, PersonalityMeta } from './types'

type AnyPersonalityId = CorePersonalityId | PremiumPersonalityId | TraitId

export const PERSONALITY_REGISTRY: Record<AnyPersonalityId, PersonalityMeta> = {
  // ── Premium ──────────────────────────────────────────────────────────────
  quiet_millionaire: {
    id: 'quiet_millionaire',
    name: 'The Quiet Millionaire',
    tagline: 'High income, low spend, says nothing. The most dangerous kind of wealthy.',
    vibe: 'The quietest number in the room is usually the largest.',
    accent: '#F59E0B', accentBg: 'rgba(245,158,11,0.08)',
    isCaution: false, isPremium: true, isDisabled: false,
  },
  strategic_deployer: {
    id: 'strategic_deployer',
    name: 'The Strategic Deployer',
    tagline: 'Every dollar has a job. Nothing sits idle, nothing gets wasted.',
    vibe: 'Precision isn\'t a personality. It\'s a practice.',
    accent: '#818CF8', accentBg: 'rgba(129,140,248,0.10)',
    isCaution: false, isPremium: true, isDisabled: false,
  },
  compounding_machine: {
    id: 'compounding_machine',
    name: 'The Compounding Machine',
    tagline: 'Money quietly stacking on itself — you built something that works while you sleep.',
    vibe: 'You\'re not saving money. You\'re buying future time.',
    accent: '#34D399', accentBg: 'rgba(52,211,153,0.08)',
    isCaution: false, isPremium: true, isDisabled: true,  // needs multi-month data
  },

  // ── Core — Universal ─────────────────────────────────────────────────────
  full_send: {
    id: 'full_send',
    name: 'The Full Send',
    tagline: 'You spent more than you earned this month. No judgment — just awareness.',
    vibe: 'Full throttle. Just make sure the tank refills.',
    accent: '#F97316', accentBg: 'rgba(249,115,22,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  wire_dancer: {
    id: 'wire_dancer',
    name: 'The Wire Dancer',
    tagline: 'You cleared the month by the skin of your teeth.',
    vibe: 'Tight margin, clean finish.',
    accent: '#2DD4BF', accentBg: 'rgba(45,212,191,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  breakeven_poet: {
    id: 'breakeven_poet',
    name: 'The Breakeven Poet',
    tagline: 'Income in, money out — almost perfectly equal. A financial haiku.',
    vibe: 'The universe balanced your books this month.',
    accent: '#C084FC', accentBg: 'rgba(192,132,252,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  adrenaline_accountant: {
    id: 'adrenaline_accountant',
    name: 'The Adrenaline Accountant',
    tagline: 'Wild swings, big moves, somehow still tracking.',
    vibe: 'You live dangerously and document everything.',
    accent: '#F43F5E', accentBg: 'rgba(244,63,94,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  chaos_controller: {
    id: 'chaos_controller',
    name: 'The Chaos Controller',
    tagline: 'The spending pattern makes no sense on paper, but you always land okay.',
    vibe: 'Controlled chaos is still controlled.',
    accent: '#FB923C', accentBg: 'rgba(251,146,60,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  big_ticket_player: {
    id: 'big_ticket_player',
    name: 'The Big Ticket Player',
    tagline: 'One category dominates your spending this period.',
    vibe: 'Intentional move, or worth a second look — you decide.',
    accent: '#F59E0B', accentBg: 'rgba(245,158,11,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  subscription_collector: {
    id: 'subscription_collector',
    name: 'The Subscription Collector',
    tagline: 'Your subscriptions are stacking up. A quick audit could pay off.',
    vibe: 'You love your services — just make sure they all still spark joy.',
    accent: '#818CF8', accentBg: 'rgba(129,140,248,0.10)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  low_key_saver: {
    id: 'low_key_saver',
    name: 'The Low-Key Saver',
    tagline: 'You keep more than half of what you earn. Quietly winning.',
    vibe: 'Steady hands, healthy balance. Keep it up.',
    accent: '#22C55E', accentBg: 'rgba(34,197,94,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  safety_buffer: {
    id: 'safety_buffer',
    name: 'The Safety Buffer',
    tagline: 'You keep a cushion between you and chaos. Smart move.',
    vibe: 'Not flashy. Just built to last.',
    accent: '#60A5FA', accentBg: 'rgba(96,165,250,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  smooth_operator: {
    id: 'smooth_operator',
    name: 'The Smooth Operator',
    tagline: 'Controlled spending, zero surprises. You make it look easy.',
    vibe: 'Strong, steady, and under control.',
    accent: '#A78BFA', accentBg: 'rgba(167,139,250,0.10)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  savvy_spender: {
    id: 'savvy_spender',
    name: 'The Savvy Spender',
    tagline: 'Balanced spending with room to grow.',
    vibe: 'You\'re in a healthy financial position this month.',
    accent: '#4F46E5', accentBg: 'rgba(79,70,229,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  flow_master: {
    id: 'flow_master',
    name: 'The Flow Master',
    tagline: 'Money moves freely — in and out. You live with confidence.',
    vibe: 'You\'re in full flow. Just watch the current.',
    accent: '#06B6D4', accentBg: 'rgba(6,182,212,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  steady_builder: {
    id: 'steady_builder',
    name: 'The Steady Builder',
    tagline: 'Consistent, controlled, and building toward something.',
    vibe: 'You\'re running a tight ship this month.',
    accent: '#6366F1', accentBg: 'rgba(99,102,241,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },

  // ── Core — Bank Specific ─────────────────────────────────────────────────
  overdraft_artist: {
    id: 'overdraft_artist',
    name: 'The Overdraft Artist',
    tagline: 'You\'ve dipped below zero but always found your way back. The margin is tight.',
    vibe: 'You\'re closer to the edge than you need to be — but you already know that.',
    accent: '#FB923C', accentBg: 'rgba(251,146,60,0.08)',
    isCaution: true, isPremium: false, isDisabled: false,
  },
  cash_keeper: {
    id: 'cash_keeper',
    name: 'The Cash Keeper',
    tagline: 'Your balance stays healthy and your spending stays measured.',
    vibe: 'Not every dollar needs to move. Some just need to sit.',
    accent: '#34D399', accentBg: 'rgba(52,211,153,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  direct_depositor: {
    id: 'direct_depositor',
    name: 'The Direct Depositor',
    tagline: 'Income comes in on schedule, spending flows out predictably. You\'ve built a rhythm.',
    vibe: 'Consistency is underrated. Yours is working.',
    accent: '#38BDF8', accentBg: 'rgba(56,189,248,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },

  // ── Core — Credit Specific ───────────────────────────────────────────────
  revolving_door: {
    id: 'revolving_door',
    name: 'The Revolving Door',
    tagline: 'A balance is carrying over month to month. Interest is quietly becoming a regular expense.',
    vibe: 'The balance doesn\'t have to stay. Worth a look at what it\'s costing you.',
    accent: '#FB923C', accentBg: 'rgba(251,146,60,0.08)',
    isCaution: true, isPremium: false, isDisabled: false,
  },
  points_chaser: {
    id: 'points_chaser',
    name: 'The Points Chaser',
    tagline: 'High volume, smart category use, paid in full. You\'re playing the system and winning.',
    vibe: 'Every swipe is a move. You know the game.',
    accent: '#FBBF24', accentBg: 'rgba(251,191,36,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  minimum_payer: {
    id: 'minimum_payer',
    name: 'The Minimum Payer',
    tagline: 'Payments are coming in just above the minimum due. The balance isn\'t shrinking fast enough.',
    vibe: 'You\'re staying current — but the interest is working harder than you are right now.',
    accent: '#FB923C', accentBg: 'rgba(251,146,60,0.08)',
    isCaution: true, isPremium: false, isDisabled: false,
  },
  cashback_architect: {
    id: 'cashback_architect',
    name: 'The Cashback Architect',
    tagline: 'Your spending is distributed in a way that suggests intent. You\'re optimizing.',
    vibe: 'Structured, deliberate, and quietly efficient.',
    accent: '#818CF8', accentBg: 'rgba(129,140,248,0.10)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  one_card_wonder: {
    id: 'one_card_wonder',
    name: 'The One Card Wonder',
    tagline: 'Everything goes on one card. Simple, clean, easy to track.',
    vibe: 'One card, one statement, one less thing to think about.',
    accent: '#94A3B8', accentBg: 'rgba(148,163,184,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  utilization_king: {
    id: 'utilization_king',
    name: 'The Utilization King',
    tagline: 'You\'re running close to your credit limit consistently. Watch the ratio.',
    vibe: 'High utilization isn\'t always a problem. But it\'s always worth knowing.',
    accent: '#FB923C', accentBg: 'rgba(251,146,60,0.08)',
    isCaution: true, isPremium: false, isDisabled: false,
  },
  balance_transfer: {
    id: 'balance_transfer',
    name: 'The Balance Transfer',
    tagline: 'Debt has moved but the clock is ticking. The window is open.',
    vibe: 'You made a smart move. Now make the most of it.',
    accent: '#FBBF24', accentBg: 'rgba(251,191,36,0.08)',
    isCaution: true, isPremium: false, isDisabled: false,
  },

  // ── Traits ───────────────────────────────────────────────────────────────
  fork_and_knife: {
    id: 'fork_and_knife',
    name: 'Fork & Knife',
    tagline: 'Food and dining lead your spending. You invest in the experience of eating well.',
    vibe: 'Life\'s too short for bad meals.',
    accent: '#F97316', accentBg: 'rgba(249,115,22,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  friday_flush: {
    id: 'friday_flush',
    name: 'Friday Flush',
    tagline: 'Entertainment and recreation top your spending — you know how to enjoy yourself.',
    vibe: 'Work hard, play harder.',
    accent: '#EC4899', accentBg: 'rgba(236,72,153,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  health_nut: {
    id: 'health_nut',
    name: 'Health Nut',
    tagline: 'Gym, supplements, and wellness spending top the chart. Your body is the portfolio.',
    vibe: 'You\'re not spending on health. You\'re investing in it.',
    accent: '#10B981', accentBg: 'rgba(16,185,129,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  morning_stack: {
    id: 'morning_stack',
    name: 'Morning Stack',
    tagline: 'Daily habits and small rituals shape your entire spending fingerprint.',
    vibe: 'Small things, done consistently, add up.',
    accent: '#D97706', accentBg: 'rgba(217,119,6,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  gear_head: {
    id: 'gear_head',
    name: 'Gear Head',
    tagline: 'Auto, fuel, and transport dominate. The vehicle is a lifestyle, not a line item.',
    vibe: 'Every mile has a price. Yours is worth it.',
    accent: '#3B82F6', accentBg: 'rgba(59,130,246,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  home_economist: {
    id: 'home_economist',
    name: 'Home Economist',
    tagline: 'Groceries, household, and essentials run your budget like clockwork.',
    vibe: 'You keep the lights on and the fridge full. That\'s no small thing.',
    accent: '#6366F1', accentBg: 'rgba(99,102,241,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  nest_builder: {
    id: 'nest_builder',
    name: 'Nest Builder',
    tagline: 'Home improvement, furniture, and decor dominate. You\'re making your space yours.',
    vibe: 'Home isn\'t a place. It\'s a project.',
    accent: '#8B5CF6', accentBg: 'rgba(139,92,246,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  frequent_flyer: {
    id: 'frequent_flyer',
    name: 'Frequent Flyer',
    tagline: 'Travel and transport sit at the top of your spending. You move.',
    vibe: 'Borders are just suggestions.',
    accent: '#F59E0B', accentBg: 'rgba(245,158,11,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  night_owl: {
    id: 'night_owl',
    name: 'Night Owl',
    tagline: 'Delivery, bars, and late-night spending tell a story about when you come alive.',
    vibe: 'The city doesn\'t sleep, and neither does your card.',
    accent: '#818CF8', accentBg: 'rgba(129,140,248,0.10)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  glow_up: {
    id: 'glow_up',
    name: 'Glow Up',
    tagline: 'Beauty, fashion, and personal care lead your spending. You invest in how you show up.',
    vibe: 'Looking good is a budget category now.',
    accent: '#A855F7', accentBg: 'rgba(168,85,247,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  grind_setter: {
    id: 'grind_setter',
    name: 'Grind Setter',
    tagline: 'Business tools, software, and workspace costs signal someone building something.',
    vibe: 'Every expense is an asset in disguise.',
    accent: '#64748B', accentBg: 'rgba(100,116,139,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  digital_native: {
    id: 'digital_native',
    name: 'Digital Native',
    tagline: 'SaaS, apps, streaming, and tech subscriptions define your spending DNA.',
    vibe: 'You live in the cloud and spend like it too.',
    accent: '#06B6D4', accentBg: 'rgba(6,182,212,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  personal_cfo: {
    id: 'personal_cfo',
    name: 'Personal CFO',
    tagline: 'Health, education, or self-care leads your spending. You invest in yourself first.',
    vibe: 'The best ROI is the one you carry with you.',
    accent: '#0EA5E9', accentBg: 'rgba(14,165,233,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  social_butterfly: {
    id: 'social_butterfly',
    name: 'Social Butterfly',
    tagline: 'Dining out, events, and gifts paint a picture of someone who shows up for people.',
    vibe: 'Generosity has a line item. Yours is healthy.',
    accent: '#EF4444', accentBg: 'rgba(239,68,68,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  card_carrier: {
    id: 'card_carrier',
    name: 'Card Carrier',
    tagline: 'Most of your real spending flows through credit cards. Your bank statement is mostly payoffs.',
    vibe: 'The card does the work. You do the living.',
    accent: '#6366F1', accentBg: 'rgba(99,102,241,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },

  // ── Discretionary spending traits ────────────────────────────────────────
  margin_eater: {
    id: 'margin_eater',
    name: 'Margin Eater',
    tagline: 'Cooked up your margins and ate them.',
    vibe: 'The table always wins.',
    accent: '#f97316', accentBg: 'rgba(249,115,22,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  cash_casserole: {
    id: 'cash_casserole',
    name: 'Cash Casserole',
    tagline: 'Baked your budget into dinner.',
    vibe: 'Dinner is served. Savings are not.',
    accent: '#fb923c', accentBg: 'rgba(251,146,60,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  drive_thru_cfo: {
    id: 'drive_thru_cfo',
    name: 'Drive Thru CFO',
    tagline: 'Arteries and accounts both clogged.',
    vibe: 'Fast food, slow recovery.',
    accent: '#ef4444', accentBg: 'rgba(239,68,68,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  liquid_assets: {
    id: 'liquid_assets',
    name: 'Liquid Assets',
    tagline: 'Liquid assets fully liquidated.',
    vibe: 'The bar never closed itself.',
    accent: '#8b5cf6', accentBg: 'rgba(139,92,246,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  daily_grind: {
    id: 'daily_grind',
    name: 'Daily Grind',
    tagline: 'Brewing my budget one cup at a time.',
    vibe: 'Consciousness has a price tag.',
    accent: '#d97706', accentBg: 'rgba(217,119,6,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  never_home: {
    id: 'never_home',
    name: 'Never Home',
    tagline: "You've never once said actually let's just stay in.",
    vibe: 'The city charges admission.',
    accent: '#ec4899', accentBg: 'rgba(236,72,153,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  delivery_regular: {
    id: 'delivery_regular',
    name: 'Delivery Regular',
    tagline: 'Your delivery driver has seen you in pajamas more than your friends have.',
    vibe: 'The doorbell knows your name.',
    accent: '#a855f7', accentBg: 'rgba(168,85,247,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  wellness_bill: {
    id: 'wellness_bill',
    name: 'Wellness Bill',
    tagline: 'The supplements cost more than the groceries.',
    vibe: 'Health is wealthy. Wallet is not.',
    accent: '#10b981', accentBg: 'rgba(16,185,129,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  free_trial_life: {
    id: 'free_trial_life',
    name: 'Free Trial Life',
    tagline: 'Free trials are a lifestyle not a savings strategy.',
    vibe: 'Cancel never felt urgent.',
    accent: '#06b6d4', accentBg: 'rgba(6,182,212,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  glowing_broke: {
    id: 'glowing_broke',
    name: 'Glowing Broke',
    tagline: "You're moisturized, exfoliated, and financially exposed.",
    vibe: 'The mirror looks great.',
    accent: '#c026d3', accentBg: 'rgba(192,38,211,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  degree_debt: {
    id: 'degree_debt',
    name: 'Degree Debt',
    tagline: 'The degree hangs on the wall, the debt hangs everywhere else.',
    vibe: 'Knowledge was supposed to pay dividends.',
    accent: '#0ea5e9', accentBg: 'rgba(14,165,233,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  mail_goes_home: {
    id: 'mail_goes_home',
    name: 'Mail Goes Home',
    tagline: 'Home is just where your mail goes.',
    vibe: 'The horizon keeps moving the price up.',
    accent: '#f59e0b', accentBg: 'rgba(245,158,11,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  corner_office: {
    id: 'corner_office',
    name: 'Corner Office',
    tagline: 'Zero salary, full benefits, corner office on the couch.',
    vibe: "They didn't ask for this lifestyle.",
    accent: '#84cc16', accentBg: 'rgba(132,204,22,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  burn_rate: {
    id: 'burn_rate',
    name: 'The Burn Rate',
    tagline: 'You rolled up your budget and smoked it.',
    vibe: 'The habit outlasted the savings.',
    accent: '#78716c', accentBg: 'rgba(120,113,108,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  heaven_sent: {
    id: 'heaven_sent',
    name: 'Heaven Sent',
    tagline: 'Heaven sent, wallet spent.',
    vibe: 'Generosity without a ceiling.',
    accent: '#ef4444', accentBg: 'rgba(239,68,68,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
  currency_combustion: {
    id: 'currency_combustion',
    name: 'Currency Combustion',
    tagline: 'Converting currency into combustion daily.',
    vibe: 'Every mile has a price tag.',
    accent: '#3b82f6', accentBg: 'rgba(59,130,246,0.08)',
    isCaution: false, isPremium: false, isDisabled: false,
  },
}

export function getPersonalityMeta(id: AnyPersonalityId): PersonalityMeta {
  return PERSONALITY_REGISTRY[id]
}
